name: Build and Push Web Docker Image to GCR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCR_CREDENTIALS }}

      - name: Configure Docker to use gcloud credentials
        run: gcloud auth configure-docker gcr.io

      - name: Set dynamic image tag (timestamp)
        id: image_tag
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build and push Docker image to GCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: gcr.io/kdt1-finalproject/web_ci:${{ env.TAG }}

      - name: Update deployment.yaml with new image tag
        run: |
          sed -i "s|image: gcr.io/kdt1-finalproject/web_ci:.*|image: gcr.io/kdt1-finalproject/web_ci:${{ env.TAG }}|" k8s/web/web-deployment.yaml

      - name: Commit and push updated deployment.yaml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/web/web-deployment.yaml
          git commit -m "Update web deployment image to ${{ env.TAG }}"
          git push

