name: Build and Push Web Docker Image to GCR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCR_CREDENTIALS }}

      - name: Configure Docker to use gcloud credentials
        run: gcloud auth configure-docker gcr.io

      - name: Build and push Docker image to GCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: gcr.io/kdt1-finalproject/web_ci:${{ github.sha }}

      - name: Update Helm appVersion and tag with numeric version
        run: |
          CURRENT_TAG=$(grep "tag:" web/values.yaml | awk '{print $2}')
          NEXT_TAG=$((CURRENT_TAG + 1))

          sed -i "s/^  tag: .*/  tag: $NEXT_TAG/" web/values.yaml
          sed -i "s/^appVersion: .*/appVersion: \"$NEXT_TAG\"/" web/Chart.yaml

      - name: Commit and Push updated Helm values
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add web/Chart.yaml web/values.yaml
          git commit -m "Update Web Helm tag to $SHORT_SHA"
          git push
